
- name: cet4
  input: origin/CET4.json
  output: dest/T4.txt
  wordPath:
    - headWord
  replace:
    world-wide: ["worldwide"]
    systematical: [systematic]
- name: cet6
  input: origin/CET6.json
  output: dest/T6.txt
  wordPath:
    - headWord
  replace:
    Thanksgiving: [thanksgiving]
- name: toefl
  input: origin/TOEFL.json
  output: dest/TF.txt
  wordPath:
    - headWord
  replace:
    lost-and-found: [lost and found]
    smelting: [smelt]
- name: ielts
  input: origin/IELTS.json
  output: dest/IS.txt
  wordPath:
    - headWord
  replace:
    a calculated crime: [a, calculate, crime]
    freefone: ["Freefone"]
    front-line: [frontline]
    inductive reasoning: [inductive, reason]
    Kung Fu: ["kung fu"]
    MasterCard: []
    overlapping: [overlap]
    utilisation: ["utilization"]
    water-borne: [waterborne]
    world-wide: ["worldwide"]
    solar-powered: [solar power]
- name: sat
  input: origin/SAT.json
  output: dest/ST.txt
  wordPath:
    - headWord
  replace:
    Aluminum: [aluminum]
    antibiotics: ["antibiotic"]
    blase: ["blasé"]
    Iron: ["iron"]
    Oxygen: ["oxygen"]
    cooling: [cool]
    attache: [attaché]
    comestibles: [comestible]
- name: gmat
  input: origin/GMAT.json
  output: dest/GM.txt
  wordPath:
    - headWord
  replace:
    antibiotics: ["antibiotic"]
    compensatorily: [compensatory]
    et al: [et al.]
    etched: [etch]
    inverted: ["invert"]
    mass-transit: ["mass transit"]
    mosaics: ["mosaic"]
    paleolithic: ["Paleolithic"]
    repousse: [repoussé]
    single-entry: ["single entry"]
    spiced: [spice]
    unreimbursed: ["reimburse"]
    upholstered: [upholster]
    vertice: ["vertex"]
    vortices: [vortex]
- name: bec
  input: origin/BEC.json
  output: dest/BE.txt
  wordPath:
    - headWord
  replace:
    averaging: ["average"]
    CBA: []
    counterfeits: ["counterfeit"]
    counting: [count]
    dictaphone: ["Dictaphone"]
    ERP: []
    facilities: [facility]
    finances: [finance]
    HRD: []
    overvalued: ["overvalue"]
    papers: [paper]
    results: [result]
    savings: [saving]
    ungeared: ["ungear"]
    XD: []