
- name: npee
  path: origin/KaoYan_1.json
  tag: KY
  wordPath:
    - headWord
- name: npee
  path: origin/KaoYan_2.json
  tag: KY
  wordPath:
    - headWord
  replace:
    goodby: [goodbye]
    april: ["April"]
- name: npee
  path: origin/KaoYan_3.json
  tag: KY
  wordPath:
    - headWord
  replace:
    encyclopaedia: [encyclopedia]
    resumé: [résumé]
    by-pass: ["bypass"]
- name: cet4
  path: origin/CET4_1.json
  tag: T4
  wordPath:
    - headWord
- name: cet4
  path: origin/CET4_2.json
  tag: T4
  wordPath:
    - headWord
  replace:
    reservior: [reservoir]
- name: cet4
  path: origin/CET4_3.json
  tag: T4
  wordPath:
    - headWord
- name: cet6
  path: origin/CET6_1.json
  tag: T6
  wordPath:
    - headWord
  replace:
    Automatically: ["automatically"]
- name: cet6
  path: origin/CET6_2.json
  tag: T6
  wordPath:
    - headWord
  replace:
    Heaven: ["heaven"]
- name: cet6
  path: origin/CET6_3.json
  tag: T6
  wordPath:
    - headWord
- name: toefl
  path: origin/TOEFL_2.json
  tag: TF
  wordPath:
    - headWord
  replace:
    Health: ["health"]
    Himalaya: [Himalayas]
    Interstate: ["interstate"]
    Yucatan: []
    Isle: ["isle"]
    Lowa: ["lowa"]
    allende: []
    antarctica: ["Antarctica"]
    appalachian: ["Appalachian"]
    beng: []
    bryn: []
    baedeker: []
    balkan: ["Balkan"]
    beringia: ["Beringia"]
    brea: []
    brewster: []
    broadway: ["Broadway"]
    boxlike: ["box"]
    conestoga: [Conestoga wagon]
    datebase: [database]
    duchenne: []
    dy: []
    eka: [eka-]
    eletricity: [electricity]
    elliot: []
    erectus: []
    faunal: [fauna]
    guilde: [guild, guilder]
    keplerian: []
    lesley: []
    loder: []
    lumiere: []
    lvory: [ivory]
    lys: []
    merchandis: [merchandise]
    midocean: []
    misinterprete: [misinterpret]
    newberry: []
    nowcasting: []
    nss: []
    ogallala: []
    permineralization: []
    rainer: [trainer]
    sargeant: [sergeant]
    semimolten: []
    zagros: [Zagros Mountains]
- name: toefl
  path: origin/TOEFL_3.json
  tag: TF
  wordPath:
    - headWord
- name: ielts
  path: origin/IELTS_2.json
  tag: IS
  wordPath:
    - headWord
  replace:
    aupair: []
    relinguish: [relinquish]
    groa: []
    chiche: []
- name: ielts
  path: origin/IELTS_3.json
  tag: IS
  wordPath:
    - headWord
  replace:
    Kung Fu: ["kung fu"]
    inductive reasoning: [inductive, reason]
    a calculated crime: [a, calculate, crime]
- name: sat
  path: origin/SAT_3.json
  tag: ST
  wordPath:
    - headWord
  replace:
    Aluminum: [aluminum]
    AluminumAl: [aluminum]
    Iron Fe: [iron]
    Iron: ["iron"]
    Oxygen O: [oxygen]
    Oxygen: ["oxygen"]
    PhosphorusP: [phosphorus]
    a. 灵巧的， 熟练的: [skillful]
    anaerobic respiration: [anaerobic, respiration]
    ante-room: ["anteroom"]
    artificial fertilization: [artificial, fertilization]
    blase: ["blasé"]
    distingusihed: [distinguished]
    homologous chromosome: [homologous, chromosome]
    parallel lines: [parallel, line]
    projector lens: [projector, lens]
    prokaryotic cell: [prokaryotic, cell]
    sulfur disoxide: [sulfur dioxide]
    temperate forest: [temperate, forest]
    temperate grassland: [temperate, grassland]
    transgenic animals: [transgenic, animal]
    undersize d: [undersized]
- name: gre
  path: origin/GRE_2.json
  tag: GR
  wordPath:
    - headWord
  replace:
    'n': []
    absinth: ["absinthe"]
    blase: ["blasé"]
    quizzable: [quiz]
    tecnology: [technology]
    neodoxy: []
- name: gre
  path: origin/GRE_3.json
  tag: GR
  wordPath:
    - headWord
  replace:
    cosycozy: [cozy]
    sun-bronzed: [sun, bronzed]
    self-adulation: [self, adulation]
    self-procession: [self, procession]
    idiosyncracy: [idiosyncrasy]
    ill-paying: [ill, pay]
- name: gmat
  path: origin/GMAT_2.json
  tag: GM
  wordPath:
    - headWord
- name: gmat
  path: origin/GMAT_3.json
  tag: GM
  wordPath:
    - headWord
- name: bec
  path: origin/BEC_2.json
  tag: BE
  wordPath:
    - headWord
  replace:
    HRD: []
    CBA: []
    XD: []
    averaging: ["average"]
- name: bec
  path: origin/BEC_3.json
  tag: BE
  wordPath:
    - headWord
  replace:
    CBA: []
    Encl.: ["encl."]
    HRD: []
    XD: []
    averaging: ["average"]
    b/e: ["BE"]
    back-up: ["backup"]
    fast-expanding: [fast, expand]
    lineskipper: [line, skipper]
    over-demand: [over, demand]
    pseudo-academic: [pseudo, academic]
