- name: sat
  path: origin/SAT_3.json
  tag: ST
  wordPath:
    - headWord
  replace:
    Aluminum: [aluminum]
    AluminumAl: [aluminum]
    Iron Fe: [iron]
    Iron: ["iron"]
    Oxygen O: [oxygen]
    Oxygen: ["oxygen"]
    PhosphorusP: [phosphorus]
    a. 灵巧的， 熟练的: [skillful]
    anaerobic respiration: [anaerobic, respiration]
    ante-room: ["anteroom"]
    artificial fertilization: [artificial, fertilization]
    blase: ["blasé"]
    distingusihed: [distinguished]
    homologous chromosome: [homologous, chromosome]
    parallel lines: [parallel, line]
    projector lens: [projector, lens]
    prokaryotic cell: [prokaryotic, cell]
    sulfur disoxide: [sulfur dioxide]
    temperate forest: [temperate, forest]
    temperate grassland: [temperate, grassland]
    transgenic animals: [transgenic, animal]
    undersize d: [undersized]
- name: gre
  path: origin/GRE_2.json
  tag: GR
  wordPath:
    - headWord
  replace:
    'n': []
    absinth: ["absinthe"]
    blase: ["blasé"]
    quizzable: [quiz]
    tecnology: [technology]
    neodoxy: []
- name: gre
  path: origin/GRE_3.json
  tag: GR
  wordPath:
    - headWord
  replace:
    cosycozy: [cozy]
    sun-bronzed: [sun, bronzed]
    self-adulation: [self, adulation]
    self-procession: [self, procession]
    idiosyncracy: [idiosyncrasy]
    ill-paying: [ill, pay]
- name: gmat
  path: origin/GMAT_2.json
  tag: GM
  wordPath:
    - headWord
- name: gmat
  path: origin/GMAT_3.json
  tag: GM
  wordPath:
    - headWord
- name: bec
  path: origin/BEC_2.json
  tag: BE
  wordPath:
    - headWord
  replace:
    HRD: []
    CBA: []
    XD: []
    averaging: ["average"]
- name: bec
  path: origin/BEC_3.json
  tag: BE
  wordPath:
    - headWord
  replace:
    CBA: []
    Encl.: ["encl."]
    HRD: []
    XD: []
    averaging: ["average"]
    b/e: ["BE"]
    back-up: ["backup"]
    fast-expanding: [fast, expand]
    lineskipper: [line, skipper]
    over-demand: [over, demand]
    pseudo-academic: [pseudo, academic]
