- name: gmat
  input: origin/GMAT_2.json
  output: GM
  wordPath:
    - headWord
- name: gmat
  input: origin/GMAT_3.json
  output: GM
  wordPath:
    - headWord
- name: bec
  input: origin/BEC_2.json
  output: BE
  wordPath:
    - headWord
  replace:
    HRD: []
    CBA: []
    XD: []
    averaging: ["average"]
- name: bec
  input: origin/BEC_3.json
  output: BE
  wordPath:
    - headWord
  replace:
    CBA: []
    Encl.: ["encl."]
    HRD: []
    XD: []
    averaging: ["average"]
    b/e: ["BE"]
    back-up: ["backup"]
    fast-expanding: [fast, expand]
    lineskipper: [line, skipper]
    over-demand: [over, demand]
    pseudo-academic: [pseudo, academic]
