# case replace
"FALSE": ["false"]
"TRUE": ["true"]
christian: ["Christian"]
december: ["December"]
dictaphone: ["Dictaphone"]
i: ["I"]
# variants to common
Mr: ["Mr."]
Mrs: ["Mrs."]
Ms: ["Ms."]
# month
Jan.: [Jan]
Feb.: [Feb]
Mar.: [Mar]
Jun.: [Jun]
Jul.: [Jul]
Aug.: [Aug]
Sep.: [Sep]
Oct.: [Oct]
Nov.: [Nov]
Dec.: [Dec]
Sept.: [Sept]
# lemmatize
antibiotics: ["antibiotic"]
# unconfirmed
um.: ["um"]
un-american: ["un-American"]
unaffordability: ["affordable"]
unauthorize: ["authorize"]
unbearably: ["unbearable"]
unclogged: ["unclog"]
uncoupling: ["uncouple"]
underestimated: ["underestimate"]
underlies: ["underlie"]
undernourishment: ["undernourished"]
underreporting: ["underreport"]
understandingly: ["understanding"]
undertaken: ["undertake"]
undie: ["undies"]
unethically: ["unethical"]
unfavorably: ["unfavorable"]
unfollowed: ["unfollow"]
unforgetable: ["unforgettable"]
ungated: ["gated"]
ungeared: ["ungear"]
unimaginably: ["unimaginable"]
unimaginatively: ["unimaginative"]
unions: ["union"]
universities: ["university"]
unix: ["UNIX"]
unknowingly: ["unknowing"]
unlawfulness: ["unlawful"]
unnaturally: ["unnatural"]
unpleasantly: ["unpleasant"]
unprofessionally: ["unprofessional"]
unreasonableness: ["unreasonable"]
unreimbursed: ["reimburse"]
unruliness: ["unruly"]
unselfishly: ["unselfish"]
unspeakably: ["unspeakable"]
unspoilt: ["spoilt"]
unstabilized: ["stabilize"]
updater: ["update"]
upper-level: ["upper"]
uranus: ["Uranus"]
urethral: ["urethra"]
urged: ["urge"]
users: ["user"]
uses: ["use"]
using: ["use"]
utilisation: ["utilization"]
utilized: ["utilize"]
v-shape: ["V-shaped"]
vaguest: ["vague"]
value-based: ["value"]
values: ["value"]
vanished: ["vanish"]
variables: ["variable"]
variations: ["variation"]
varieties: ["variety"]
varnished: ["varnish"]
varying: ["vary"]
vegetables: ["vegetable"]
vehicles: ["vehicle"]
ventilated: ["ventilate"]
venus: ["Venus"]
verbalizable: ["verbalize"]
versions: ["version"]
vertice: ["vertices"]
vessels: ["vessel"]
vice-president: ["vice president"]
victimized: ["victimize"]
victims: ["victim"]
video-taped: ["videotape"]
videos: ["video"]
videotaped: ["videotape"]
videotaping: ["videotape"]
viennese: ["Viennese"]
viewed: ["view"]
views: ["view"]
villages: ["village"]
virgo: ["Virgo"]
visa-free: ["visa"]
viscerally: ["visceral"]
visited: ["visit"]
visitors: ["visitor"]
visits: ["visit"]
vocally: ["vocal"]
voiceover: ["voice-over"]
voices: ["voice"]
volumes: ["volume"]
volunteers: ["volunteer"]
vomiting: ["vomit"]
voted: ["vote"]
voters: ["voter"]
votes: ["vote"]
vulval: ["vulva"]
wading: ["wade"]
waited: ["wait"]
walk-out: ["walkout"]
walked: ["walk"]
walkman: ["Walkman"]
walks: ["walk"]
walls: ["wall"]
wanderings: ["wandering"]
wants: ["want"]
warmed: ["warm"]
warned: ["warn"]
wars: ["war"]
washed: ["wash"]
watched: ["watch"]
watching: ["watch"]
waterboy: ["water boy"]
watercourses: ["watercourse"]
waters: ["Waters"]
wavenumber: ["wave number"]
waves: ["wave"]
waxes: ["wax"]
waywardness: ["wayward"]
weaponized: ["weaponize"]
weapons: ["weapon"]

weeks: ["week"]
weight-lifting: ["weight lifter"]
welcomed: ["welcome"]
welcoming: ["welcome"]
welded: ["weld"]
weldon: ["Weldon"]
welland: ["Welland"]
wetted: ["wet"]
whirring: ["whir"]
white-out: ["whiteout"]
wi-fi: ["Wi-Fi"]
wider: ["wide"]
wilfulness: ["wilful"]
windows: ["window"]
winds: ["wind"]
wines: ["wine"]
wingnut: ["wing nut"]
winners: ["winner"]
wintering: ["winter"]
wiped: ["wipe"]
wirelessly: ["wireless"]
wished: ["wish"]
wishes: ["wish"]
witnessed: ["witness"]
witnesses: ["witness"]
wondered: ["wonder"]
woodie: ["woody"]
woods: ["wood"]
workers: ["worker"]
workshops: ["workshop"]
world-wide: ["worldwide"]
worldliness: ["worldly"]
worlds: ["world"]
wounds: ["wound"]
writers: ["writer"]
writes: ["write"]
writings: ["writing"]
x-rays: ["x-ray"]
yards: ["yard"]
yardwork: ["yard work"]
years-long: ["yearslong"]
years: ["year"]
yellowfin: ["yellowfin tuna"]
yellowstone: ["Yellowstone"]
youngsters: ["youngster"]
youthfulness: ["youthful"]
zero-point: ["zero-point energy"]
ziploc: ["Ziploc"]
zones: ["zone"]
zoot: ["zoot suit"]
# split same spell
approximate: ["approximate_1", "approximate_2"]
articulate: ["articulate_1", "articulate_2"]
bass: ["bass_1", "bass_2"]
bow: ["bow_1", "bow_2"]
buffet: ["buffet_1", "buffet_2"]
content: ["content_1", "content_2"]
contest: ["contest_1", "contest_2"]
contrast: ["contrast_1", "contrast_2"]
cos: ["cos_1", "cos_2"]
curate: ["curate_1", "curate_2"]
excerpt: ["excerpt_1", "excerpt_2"]
export: ["export_1", "export_2"]
insult: ["insult_1", "insult_2"]
lead: ["lead_1", "lead_2"]
leading: ["leading_1", "leading_2"]
live: ["live_1", "live_2"]
lower: ["lower_1", "lower_2"]
moderate: ["moderate_1", "moderate_2"]
progress: ["progress_1", "progress_2"]
purport: ["purport_1", "purport_2"]
record: ["record_1", "record_2"]
row: ["row_1", "row_2"]
sewer: ["sewer_1", "sewer_2"]
tear: ["tear_1", "tear_2"]
transfer: ["transfer_1", "transfer_2"]
transport: ["transport_1", "transport_2"]
wind: ["wind_1", "wind_2"]
survey: ["survey_1", "survey_2"]
suspect: ["suspect_1", "suspect_2"]