export class Tags extends Set<string> {
    static encoder: Record<string, string> = {
        ogden:      'OG',
        macmillan:  'MC',
        longmand:   'LD',
        longmanS1:  'S1',
        longmanS2:  'S2',
        longmanS3:  'S3',
        longmanW1:  'W1',
        longmanW2:  'W2',
        longmanW3:  'W3',
        voa:        'VA',
        wik:        'WK',
        oxfordA1:   'A1',
        oxfordA2:   'A2',
        oxfordB1:   'B1',
        oxfordB2:   'B2',
        oxfordC1:   'C1',
        oxfordC2:   'C2',
        collins1:   'L1',
        collins2:   'L2',
        collins3:   'L3',
        collins4:   'L4',
        collins5:   'L5',
        ngsl:       'GL',
        ngsls:      'GS',
        nawl:       'AW',
        tsl:        'TS',
        bsl:        'BS',
        ndl:        'DL',
        fel:        'FE',
        coca:       'CA',
        bnc:        'BN',
        hsee:       'ZK',
        ncee:       'GK',
        npee:       'KY',
        cet4:       'T4',
        cet6:       'T6',
        toefl:      'TF',
        ielts:      'IS',
        sat:        'ST',
        gre:        'GR',
        gmat:       'GM',
        bec:        'BE'
    }
    static decoder: Record<string, string> = {
        OG: 'Ogden',
        MC: 'Macmillan',
        LD: 'LangmanD',
        S1: 'LangmanS1',
        S2: 'LangmanS2',
        S3: 'LangmanS3',
        W1: 'LangmanW1',
        W2: 'LangmanW2',
        W3: 'LangmanW3',
        VA: 'VOA1500',
        WK: 'Wik1000',
        A1: 'OxfordA1',
        A2: 'OxfordA2',
        B1: 'OxfordB1',
        B2: 'OxfordB2',
        C1: 'OxfordC1',
        C2: 'OxfordC2',
        L1: 'Collins1',
        L2: 'Collins2',
        L3: 'Collins3',
        L4: 'Collins4',
        L5: 'Collins5',
        GL: 'NGSL',
        GS: 'NGSLS',
        AW: 'NAWL',
        TL: 'TSL',
        BL: 'BSL',
        DL: 'NDL',
        FE: 'FEL',
        CA: 'COCA',
        BN: 'BNC',
        ZK: 'HSEE',
        GK: 'NECC',
        KY: 'NPEE',
        T4: 'CET4',
        T6: 'CET6',
        TF: 'Toefl',
        IS: 'Ietls',
        ST: 'SAT',
        GR: 'GRE',
        GM: 'GMAT',
        BE: 'BEC'
    }
    attach(tags: Iterable<string>) {
        for (const tag of tags) this.add(tag);
    }
    remove(tags: Iterable<string>) {
        for (const tag of tags) this.delete(tag);
    }
    toString() {
        return Array.from(this).sort().join(',');
    }
}