%YAML 1.2
---
# yaml-language-server: $schema=https://json-schema.org/draft-04/schema
$id: "https://micinfotech.com/glossary/import-config.schema.json"
title: Import Config
description: "import configure file, import tool will work base it."
definitions:
  regex:
    type: array
    items:
      type: string
    minItems: 1
    maxItems: 2
type: object
properties:
  inputs:
    type: array
    items:
      type: object
      properties:
        path:
          type: string
        jsonPath:
          type: array
          items:
            anyOf:
              - type: string
              - type: number
        isWholeJson:
          type: boolean
        replaces:
          type: array
          items:
            oneOf:
              - $ref: "#/definitions/regex"
              - type: string
          minItems: 1
          maxItems: 2
        test:
          $ref: "#/definitions/regex"
        separator:
          type: string
      required:
        - path
  debug:
    type: boolean
  revision:
    type: string
  outputPath:
    type: string
  outputs:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        test:
          $ref: "#/definitions/regex"
required:
  - inputs
